#New roles
CREATE ROLE GROWTOPIANOWNER;
CREATE ROLE CUSTOMER;

#Set permissions for Owners
GRANT ALL ON OWNER TO GROWTOPIANOWNER;
GRANT ALL ON ITEM TO GROWTOPIANOWNER;
GRANT ALL ON WORLD TO GROWTOPIANOWNER;
GRANT ALL ON DIGIVEND_MACHINE TO GROWTOPIANOWNER;
GRANT ALL ON LOCALE TO GROWTOPIANOWNER;
GRANT ALL ON WORLD_LOCK TO GROWTOPIANOWNER;
GRANT ALL ON VEND_REVENUE TO GROWTOPIANOWNER;
GRANT ALL ON CUSTOMER TO GROWTOPIANOWNER;
GRANT ALL ON VEND_SALES TO GROWTOPIANOWNER;
GRANT ALL ON SUPPLIER TO GROWTOPIANOWNER;
GRANT ALL ON TRADE TO GROWTOPIANOWNER;
GRANT ALL ON ALLCUSTOMERS TO GROWTOPIANOWNER;
GRANT ALL ON ALLOWNERS TO GROWTOPIANOWNER;
GRANT ALL ON ALLSALES TO GROWTOPIANOWNER;


#Set permissions for Customers
GRANT SELECT ON ALLWORLDS TO CUSTOMER;
GRANT SELECT ON ALLVENDINGMACHINES TO CUSTOMER;