#Define tables and constraints 
CREATE TABLE OWNER (
    GrowID VARCHAR(18) NOT NULL UNIQUE,
    Country VARCHAR(56) NOT NULL,
    Owner_Level INT NOT NULL,
    Account_Creation_Days INT NOT NULL,
    PRIMARY KEY (GrowID),
    CONSTRAINT CHK_LEVEL_RANGE CHECK(Owner_Level > 1 AND Owner_Level <= 125),
    CONSTRAINT CHK_GROWID_LENGTH CHECK (LENGTH(GrowID) > 3)
);

CREATE TABLE ITEM (
    Item_Name VARCHAR(50) NOT NULL,
    Rarity INT NOT NULL,
    Owner_GrowID VARCHAR(18) NOT NULL,
    PRIMARY KEY (Item_Name),
    FOREIGN KEY (Owner_GrowID) REFERENCES OWNER (GrowID) ON UPDATE CASCADE,
    CONSTRAINT CHK_RARITYRANGE CHECK (Rarity >= 1 AND Rarity <= 363)
);

CREATE TABLE WORLD (
    World_Name VARCHAR(24) NOT NULL,
    Category VARCHAR(24),
    Owner_GrowID VARCHAR(18),
    PRIMARY KEY (World_Name),
    FOREIGN KEY (Owner_GrowID) REFERENCES OWNER (GrowID) ON UPDATE CASCADE,
    CONSTRAINT CHK_WORLD_NAME_LENGTH CHECK (LENGTH(World_Name) > 1)
);

CREATE TABLE DIGIVEND_MACHINE (
    Vend_ID INT NOT NULL UNIQUE,
    Price INT,
    Quantity INT,
	Item_Name VARCHAR(50),
    PRIMARY KEY (Vend_ID),
    FOREIGN KEY (Item_Name) REFERENCES ITEM (Item_Name) ON UPDATE CASCADE,
	CONSTRAINT CHK_QUANTITY CHECK (Quantity >= 0)
);

CREATE TABLE LOCALE (
    World_Name VARCHAR(24) NOT NULL,
    Vend_ID INT NOT NULL UNIQUE,
    PRIMARY KEY (World_Name, Vend_ID),
    FOREIGN KEY (World_Name) REFERENCES WORLD (World_Name) ON UPDATE CASCADE,
    FOREIGN KEY (Vend_ID) REFERENCES DIGIVEND_MACHINE (Vend_ID) ON UPDATE CASCADE
);


CREATE TABLE WORLD_LOCK (
    Lock_ID INT NOT NULL UNIQUE,
    Lock_Type VARCHAR(24) NOT NULL,
    PRIMARY KEY (Lock_ID)
);

CREATE TABLE VEND_REVENUE (
    Vend_ID INT NOT NULL UNIQUE,
	Lock_ID INT NOT NULL UNIQUE,
    PRIMARY KEY (Vend_ID, Lock_ID),
    FOREIGN KEY (Vend_ID) REFERENCES DIGIVEND_MACHINE (Vend_ID) ON UPDATE CASCADE,
    FOREIGN KEY (Lock_ID) REFERENCES WORLD_LOCK (Lock_ID) ON UPDATE CASCADE
);

CREATE TABLE CUSTOMER (
    Customer_GrowID VARCHAR(18) NOT NULL UNIQUE,
	Country VARCHAR(56) NOT NULL,
    Customer_Level INT NOT NULL,
    PRIMARY KEY (Customer_GrowID),
	CONSTRAINT CHK_CUSTOMER_LEVEL_RANGE CHECK(Customer_Level <= 125),
    CONSTRAINT CHK_CUSTOMER_GROWID_LENGTH CHECK (LENGTH(Customer_GrowID) > 3)
);


CREATE TABLE VEND_SALES (
    Vend_ID INT NOT NULL UNIQUE,
    Customer_GrowID VARCHAR(18) NOT NULL UNIQUE,
    PRIMARY KEY (Vend_ID, Customer_GrowID),
    FOREIGN KEY (Vend_ID) REFERENCES DIGIVEND_MACHINE (Vend_ID) ON UPDATE CASCADE,
    FOREIGN KEY (Customer_GrowID) REFERENCES CUSTOMER (Customer_GrowID) ON UPDATE CASCADE
);


CREATE TABLE SUPPLIER (
    Supplier_GrowID VARCHAR(18) NOT NULL UNIQUE,
	Country VARCHAR(56) NOT NULL,
    Supplier_Level INT NOT NULL,
    PRIMARY KEY (Supplier_GrowID),
    CONSTRAINT CHK_SUPPLIER_GROWID_LENGTH CHECK (LENGTH(Supplier_GrowID) > 3),
    CONSTRAINT CHK_SUPPLIER_LEVEL_RANGE CHECK(Supplier_Level <= 125)
);

CREATE TABLE TRADE (
	Item_Name VARCHAR(50) NOT NULL,
    Supplier_GrowID VARCHAR(18) NOT NULL UNIQUE,
    PRIMARY KEY (Item_Name, Supplier_GrowID),
    FOREIGN KEY (Item_Name) REFERENCES ITEM (Item_Name) ON UPDATE CASCADE,
    FOREIGN KEY (Supplier_GrowID) REFERENCES SUPPLIER (Supplier_GrowID) ON UPDATE CASCADE
);

